application: hamiltonnhs
version: 1
runtime: python27
threadsafe: false
api_version: 1

handlers:
- url: /css
  static_dir: template/css
  
- url: /js
  static_dir: template/js
  
- url: /images
  static_dir: images
  
- url: .*
  script: main.py
